const colourTypeMapping = [
  { type: "normal", color: "bg-orange-700" },
  { type: "fighting", color: "bg-red-800" },
  { type: "flying", color: "bg-purple-600" },
  { type: "poison", color: "bg-pink-800" },
  { type: "ground", color: "bg-yellow-600" },
  { type: "rock", color: "bg-yellow-800" },
  { type: "bug", color: "bg-green-600" },
  { type: "ghost", color: "bg-purple-900" },
  { type: "steel", color: "bg-gray-600" },
  { type: "fire", color: "bg-orange-500" },
  { type: "water", color: "bg-blue-500" },
  { type: "grass", color: "bg-green-800" },
  { type: "electric", color: "bg-yellow-500" },
  { type: "psychic", color: "bg-pink-600" },
  { type: "ice", color: "bg-blue-300" },
  { type: "dragon", color: "bg-purple-400" },
  { type: "dark", color: "bg-orange-900" },
  { type: "fairy", color: "bg-pink-300" },
  { type: "unknown", color: "bg-gray-500" },
  { type: "shadow", color: "bg-gray-700" },
]
